### PR TITLE
Address changes in PD: Project Management Standards changes

### LINKED ISSUE #1: Improvement should be seen as an enhancement label
The [PD Project Managment Standard](https://docs.google.com/document/d/1ZhsrX1Sz7bhOJ25nngGRuYlXfjfpv6kuvCS3T4KDtWI/edit) say that "improvement" is an enhancement  label that should be green, but pd-cli insists it is a "component/misc label" label that should be purple.

```
 - Error: [improvement] should have color #5319e7
```

### PR DESCRIPTION
**Pull request by mostlygeek**
Key changes: 

- Removed Milestone checking code in favor of Project checking
- Cleaned up error reporting
- Switch from using `*obj.Value` pattern in the previous `go-github` library to `obj.GetValue()` pattern
- Updated dependencies with `dep ensure -update`
- Fix #1 #2 #3

### CODE REVIEW

**Comment by mythmon** [comment]
I don't know Go very well, but the code changes look good at a glance. I ran the new code against mozilla/normandy, and #1 and #2 were fixed, but the behavior described in #3 is still there (no error is given when the repository is left out entirely).

**Review by mythmon — CHANGES_REQUESTED** [review]
I don't know Go very well, but the code changes look good at a glance. I ran the new code against mozilla/normandy, and #1 and #2 were fixed, but the behavior described in #3 is still there (no error is given when the repository is left out entirely).

**Comment by mythmon** [comment]
Previously when running an incomplete command like `pd-cli repo`, I would get a help page telling me where I could go from there. Now I get this:

```
$ pd-cli repo 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/mozilla/pd-cli/command/repo.preflight(0xc4200a0580, 0xc4200a0500, 0x2)
	/home/mythmon/go/src/github.com/mozilla/pd-cli/command/repo/init.go:57 +0x398
github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc4200809c0, 0xc4200a0420, 0x0, 0x0)
	/home/mythmon/go/src/github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli.v1/app.go:366 +0xacb
github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0x809f8f, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x815bb5, 0x23, 0x0, ...)
	/home/mythmon/go/src/github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x944
github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x809f8f, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x815bb5, 0x23, 0x0, ...)
	/home/mythmon/go/src/github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x1319
github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420080820, 0xc420092000, 0x2, 0x2, 0x0, 0x0)
	/home/mythmon/go/src/github.com/mozilla/pd-cli/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6f8
main.main()
	/home/mythmon/go/src/github.com/mozilla/pd-cli/cli.go:16 +0x11d
```

**Comment by mostlygeek** [comment]
Dug into this a bit deeper. Issues #1, #2 and #3 should be fixed now. 
Definitely writing this a bit faster / looser made refactoring things more adventurous.

**Comment by mostlygeek** [comment]
Fixed the runtime issue too since I i didn't do a range check on the arguments array.

**Review by mythmon — APPROVED** [review]

**Comment by mythmon** [comment]
This looks good to me, and all the issues mentioned are fixed as far as I can tell.

**Pull request merged**
